### ISSUE TITLE
packaged chrome extension fails on latest Chrome

### ISSUE THREAD

**Issue by lizthegrey** [trezor/trezor-chrome-extension#10]
localStorage deprecation has hit, and thus the existing packaged extension is busted. Can you update to a more recent build?

**Comment by prusnak** [comment]
@runn1ng ?

**Comment by karelbilek** [comment]
hey

I am not sure we use localStorage anywhere. There is the error that chrome spits, but that's because of some deep dependency, that is traversiong window.* for checking of... something.

Or is it broken completely?

**Comment by lizthegrey** [comment]
It seems to be broken completely [fails to detect my trezor across multiple devices -- chromeos and linux], and javascript errors are showing. it's possible the two are not related.

**Comment by karelbilek** [comment]
Oh, great. :/ Thanks for reporting. I will look at it today.

The JS errors are from this issue

https://github.com/ljharb/object-keys/issues/34

https://github.com/ljharb/object-keys/blob/master/index.js#L46-L63

**Comment by prusnak** [comment]
@lizthegrey Chrome version? I am on Chromium 55, I can see the errors, but everything works correctly (at least that's what it seems).

**Comment by lizthegrey** [comment]
Version 54.0.2840.101 (64-bit) on my chromebook, will get you version from my desktop in a bit.

**Comment by lizthegrey** [comment]
54.0.2840.50 beta (64-bit) on my desktop

**Comment by lizthegrey** [comment]
wait, nevermind -- this is a bad cable :) - it works after all.

**Comment by karelbilek** [comment]
That error issue is still annoying, but there is not much I can do, either on chrome side or object-keys side.
