### ISSUE TITLE
recovery fails with cannot read property message

### ISSUE THREAD

**Issue by mruddy** [trezor/trezor-chrome-extension#12]
Using the Chrome extension (downloaded from the chrome store today), I wipe the Trezor and then attempt to run the recovery.

Every time, without regard to the input values, I receive a "Cannot read property 'name' of undefined" message when I click continue (see screenshot). This is easiest to reproduce when the PIN protection is unchecked because then you don't have to enter a PIN to get the failure.

![bug](https://cloud.githubusercontent.com/assets/6440430/21755885/e2845228-d5e7-11e6-9395-532290566cd7.png)

```
["log","Mon, 09 Jan 2017 02:08:23 GMT","[trezor] Sending","RecoveryDevice",{"pin_protection":false,"word_count":24,"enforce_wordlist":true}]
["log","Mon, 09 Jan 2017 02:08:23 GMT","[trezor.js event session] send : ","RecoveryDevice",{"pin_protection":false,"word_count":24,"enforce_wordlist":true}]
["error","Mon, 09 Jan 2017 02:08:24 GMT","[trezor] Error received",{"type":"error","message":"Cannot read property 'name' of undefined"}]
["log","Mon, 09 Jan 2017 02:08:24 GMT","[trezord] Received error",{}]
["log","Mon, 09 Jan 2017 02:08:24 GMT","[trezor.js event session] error : ",{}]

Google Chrome Version 55.0.2883.87 (64-bit)
Ubuntu 16.04.1 LTS
1.4.0 Trezor firmware
```

**Comment by karelbilek** [comment]
ACK

will look at it

**Comment by karelbilek** [comment]
It was a bug in the code handling protobuf=>JSON conversion. I have fixed this and will push to chrome store soon :)

**Comment by mruddy** [comment]
cool, thanks for figuring it out. i'll be sure to test it after it's available.

**Comment by karelbilek** [comment]
Pushed on chrome store.... It should be online in an hour or so

**Comment by mruddy** [comment]
Excellent, thanks. I've just verified that version 1.2.4 of the extension from the chrome store fixes this issue.
I had to remove and re-install the extension since the chrome store did not seem to have an auto-update. That's probably typical, I've just never used the chrome store before.

**Comment by karelbilek** [comment]
I never figured out how exactly does Chrome update the extensions ; it
usually takes a while to get to all users.
