### ISSUE TITLE
Setting up the Chrome extension on ubuntu, no deb packages offered.

### ISSUE THREAD

**Issue by paulpw** [trezor/trezor-chrome-extension#15]
"
 After you install the Chrome extension in TREZOR Wallet on Linux, you will be asked to install additional package (DEB or RPM), which configures UDEV rules of your system.
"
Not offered the option to install these deb packages on ubuntu install, so a link to where to down load them in docs might be useful.

**Comment by prusnak** [comment]
Why closed?

**Comment by karelbilek** [comment]
Hey, this is a bug in mytrezor that we fixed and should be live soon-ish

Anyway, the deb packages are here

https://github.com/trezor/webwallet-data/tree/master/udev

or here 

https://wallet.trezor.io/data/udev/index.html

**Comment by karelbilek** [comment]
...and the fix is live on mytrezor

**Comment by paulpw** [comment]
@prusnak I saw the fix in mytrezor and closed it :)
