### ISSUE TITLE
Can no longer pay Bitpay Invoices as they switch to BIP 70 Payment Protocol

### ISSUE THREAD

**Issue by face** [trezor/trezor-chrome-extension#19]
Bit pay has started switching to BIP 70 for payments.    They have started with loading their visa card.   Without BIP 70 support, there is no way to send money now from my Trezor to my Bitpay Visa.  https://blog.bitpay.com/payment-protocol-card-orders/

Please add payment protocol support to Trezor wallets.   With non SegWit fees so high, I exclusively use my Trezor now, but it is an issue I can no longer send payments to Bitpay.

**Comment by prusnak** [comment]
We'll do that in the web interface, but this is a low priority. Closing this issue as this is not a trezor-chrome-extension issue.
