### ISSUE TITLE
Trezor connection hierarchy

### ISSUE THREAD

**Issue by cryptosig** [trezor/trezor-chrome-extension#2]
If I have the browser plugin,  and/or a chrome extension and/or the Trezor bridge installed onto a system which will take precedence over the other? Will the different methods interfere with another method of connection? Should an install of one automatically check for and remove the others?

**Comment by slush0** [comment]
Priority is Chrome extension > Bridge > Plugin.

Anyway, public release of myTREZOR does not support Chrome extension yet.

Extension and Plugin won't interfere each to other, but Bridge should be uninstalled if Extension is in use. Unfortunately this cannot be done automatically.

**Comment by karelbilek** [comment]
to complete, the methods will not interfere and you can have all three and only the first will apply - at least that's the plan :)
