### ISSUE TITLE
Unable to Setup New Trezor: "Update failed"

### ISSUE THREAD

**Issue by xanderdunn** [trezor/trezor-chrome-extension#20]
2017 MacBook Pro.  macOS High Siera 10.13.2.  Chrome 63.0.3239.132 (64-bit).  

I'm setting up this trezor for the first time and I always get this error at trezor.io/start:
<img width="1680" alt="screen shot 2018-01-05 at 01 18 20" src="https://user-images.githubusercontent.com/1313618/34603048-20ae8050-f1b7-11e7-94f2-c84b7adb4071.png">

When I open the Chrome app directly:
<img width="929" alt="screen shot 2018-01-05 at 01 21 42" src="https://user-images.githubusercontent.com/1313618/34603060-2ed58bf6-f1b7-11e7-951b-996c724da4fb.png">
<img width="929" alt="screen shot 2018-01-05 at 01 21 27" src="https://user-images.githubusercontent.com/1313618/34603065-3227d412-f1b7-11e7-9e56-6678f1fd056f.png">

Note that I have Strict site isolation turned on in Chrome.  
Note also that I've been unable to setup the device using `trezorctl`.  See [here](https://github.com/trezor/python-trezor/issues/196).

**Comment by prusnak** [comment]
Please contact our support, Github is not a support channel.
