### ISSUE TITLE
Some error when try to build from sources

### ISSUE THREAD

**Issue by Matroskinb** [trezor/trezor-chrome-extension#23]
Repository pulled from instructions in docs.
Commands:
`make npm-install`
`make clear`
`make zip`

`rm -rf .tmp
rm -rf ../extension/management
cp -r dist ../extension/management
rm -rf ../extension/data
python3 firmware_copy.py
Traceback (most recent call last):
  File "firmware_copy.py", line 8, in <module>
    with open('data/firmware/releases.json') as data_file:    
FileNotFoundError: [Errno 2] No such file or directory: 'data/firmware/releases.json'
Makefile:41: ошибка выполнения рецепта для цели «copy-data»
make[1]: *** [copy-data] Ошибка 1
make[1]: выход из каталога «/home/matroskinb/crypto/chrome-extension/management»
Makefile:33: ошибка выполнения рецепта для цели «management_make»
make: *** [management_make] Ошибка 2`

**Comment by prusnak** [comment]
You did not clone with submodules, see here: https://github.com/trezor/trezor-chrome-extension#checking-out-sources

**Comment by Matroskinb** [comment]
@prusnak `git clone --recursive https://github.com/trezor/chrome-extension.git` i used this for pull sources before i posted issue.
