### ISSUE TITLE
Add configurable timeout

### ISSUE THREAD

**Issue by PavelNiedoba** [trezor/trezor-chrome-extension#24]
This was promised to be part of new release (issue closed), which I just installed and it's not there. I also advice development managers not to close issues before they are actually done. If it's part of next release, putting appropriate label is recommended.

**Comment by prusnak** [comment]
Feature is in the firmware. Use `trezorctl set_auto_lock_delay` to set it to the value you want.

**Comment by PavelNiedoba** [comment]
is it included in Firmware 1.6.1 ?

I get 
```
trezorctl: error: invalid choice: 'set_auto_lock_delay' (choose from 'backup_device', 'change_pin', 'clear_session', 'decrypt_keyvalue', 'decrypt_message', 'disable_passphrase', 'enable_passphrase', 'encrypt_keyvalue', 'encrypt_message', 'ethereum_get_address', 'ethereum_sign_tx', 'firmware_update', 'get_address', 'get_entropy', 'get_features', 'get_public_node', 'list', 'list_coins', 'load_device', 'ping', 'recovery_device', 'reset_device', 'self_test', 'set_homescreen', 'set_label', 'set_u2f_counter', 'sign_message', 'verify_message', 'wipe_device')
```

**Comment by prusnak** [comment]
You have old python-trezor

**Comment by PavelNiedoba** [comment]
it works for me now, usability of password manager is much better, but my father reported some difficulty while learning about python packaging, so maybe some GUI for this in future release would be appreciated

**Comment by prusnak** [comment]
Sure, I agree and it's on the roadmap.
