### ISSUE TITLE
UI improvement requests for usability

### ISSUE THREAD

**Issue by goodc0re** [trezor/trezor-chrome-extension#8]
**UI improvement requests for usability**

As a power user of password managers for many years (10+) with a very large password database that I use all day long and every day I highly recommend the following user interface improvements: 

1) On the edit entry view, the fields are very small / short.  While there is so much unused space to the right, users can not see the full contents in the fields (e.g. long URL, long passphrase, long username, lots of text in the secret note field)  Screenshot: http://imgur.com/alo8X1l 

People put a lot of content into the free text area, so it should be using as much space as possible. 
The fields should use a large percentage of the available space on the page, not a fixed value. 

2) On the left "Tags" navigation bar, decrease the font size and space used by each tag. People who really store all their passwords will have so many categories, and they will not like to scroll down very far the screen to reach them all. 

3) On the left "Tags" navigation bar, the most important feature would be to have the "Tags" Categories expand with [+]  and allow the user to see a list of entries in that category in the left navigation bar itself!  This is a feature many current popular password managers are missing, but it is crucial for speed of usability. 
People can open their most used categories on the left navigation bar with the [+] sign, and access their entries with 1 click, instead of 2 clicks (Tag and then find the entry on the right, click to edit it), VERY big usability difference! Please do not underestimate this, this is the most important change needed in this application. People will be able to see all their entries all the time, even while looking at the edit details screen of one entry on the right.  Make the application remember which categories were expanded last time it was open, if possible. 

4) Make the edit details screen the default view on the right. Do not make people click to see their information, people want to see their information all the time especially that in the custom text entry field. People need to get to this info quickly to copy paste data from it all the time, it takes too long to click on edit all the time and enter the Trezor PIN every time. 

5) Allow creation of custom fields / templates

**Comment by good-lly** [comment]
@goodc0re Hi! Thank you for improvements suggestions, we will put them in our ToDo list and take a look at it (hopefully in a short time). This issue list is not dedicated to Password Manager stuff, so we will close it here .... :wink: if you have any further ideas for improvement please do not hesitate and write to our support guys (support@satoshilabs.com), they are collecting all the feedbacks so afterwards we can do some "big picture" decision making and shaping of Password Manager.
